version: "3"
services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    env_file:
      - .env
    ports:
      - "${MINIO_HOST_PORT}:9000"
    command: server ${MINIO_DIR}

  mc:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      for i in 1 2 3; do /usr/bin/mc config host add ${MC_MINIO_NAME} http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY} && break || sleep 5; done;
      /usr/bin/mc mb ${MC_MINIO_NAME}/${S3_BUCKET};
      "

  tusp:
    depends_on:
      - minio
      - mc
    env_file:
      - .minio.env

